import type { Product, Review } from "@/lib/types/database";

export const CATEGORIES = [
  { id: "1", name: "Engine Parts", icon: "Zap" },
  { id: "2", name: "Brakes", icon: "Square" },
  { id: "3", name: "Suspension", icon: "Wind" },
  { id: "4", name: "Filters", icon: "Filter" },
  { id: "5", name: "Electrical", icon: "Lightbulb" },
  { id: "6", name: "Exterior", icon: "Layers" },
  { id: "7", name: "Interior", icon: "Home" },
  { id: "8", name: "Transmission", icon: "Gears" },
];

export const DUMMY_PRODUCTS: Product[] = [
  {
    _id: undefined,
    sku: "FILTA",
    manufacturer: "Bosch",
    name: "Premium Engine Oil Filter",
    description: "High-quality engine oil filter for better engine performance",
    longDescription:
      "Our premium engine oil filter is designed to provide maximum protection for your engine. It features advanced filtration technology that removes harmful particles and extends engine life. Made from the finest materials, this filter ensures optimal oil flow and engine efficiency.",
    price: 299,
    originalPrice: 399,
    category: "Filters",
    images: [
      "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500&h=500&fit=crop",
      "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500&h=500&fit=crop&q=80",
    ],
    specifications: [
      { key: "Thread Size", value: "M20 x 1.5" },
      { key: "Filter Type", value: "Spin-On" },
      { key: "Micron Rating", value: "10 Micron" },
      { key: "Capacity", value: "1000ml" },
    ],
    inventory: 150,
    rating: 4.8,
    reviewCount: 245,
    isFeatured: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    _id: undefined,
    sku: "BRAKB",
    manufacturer: "Brembo",
    name: "Brake Pad Set - Front Axle",
    description: "Advanced brake pads with superior stopping power",
    longDescription:
      "Professional-grade brake pads designed for enhanced braking performance. These pads feature low-dust compound and excellent heat dissipation, ensuring safe and reliable braking in all conditions. Compatible with most vehicles.",
    price: 1299,
    originalPrice: 1599,
    category: "Brakes",
    images: [
      "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=500&h=500&fit=crop",
      "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=500&h=500&fit=crop&q=80",
    ],
    specifications: [
      { key: "Type", value: "Disc Brake Pad" },
      { key: "Compound", value: "Semi-Metallic" },
      { key: "Noise Level", value: "Low" },
      { key: "Set Size", value: "For 2 Wheels" },
    ],
    inventory: 85,
    rating: 4.6,
    reviewCount: 178,
    isFeatured: true,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-02-02"),
  },
  {
    _id: undefined,
    sku: "FILTC",
    manufacturer: "K&N",
    name: "Air Intake Filter",
    description: "Reusable air filter for better fuel efficiency",
    longDescription:
      "High-performance air intake filter that improves engine breathing and fuel efficiency. Made with premium cotton-gauze material, it provides superior filtration while maintaining excellent airflow. Easy to clean and reusable for extended service life.",
    price: 799,
    originalPrice: 999,
    category: "Filters",
    images: [
      "https://images.unsplash.com/photo-1586139207252-7e90a8a08bdc?w=500&h=500&fit=crop",
      "https://images.unsplash.com/photo-1586139207252-7e90a8a08bdc?w=500&h=500&fit=crop&q=80",
    ],
    specifications: [
      { key: "Type", value: "Washable & Reusable" },
      { key: "Material", value: "Cotton-Gauze" },
      { key: "Air Flow", value: "High Flow" },
      { key: "Efficiency Gain", value: "Up to 8%" },
    ],
    inventory: 120,
    rating: 4.7,
    reviewCount: 156,
    isFeatured: true,
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-02-03"),
  },
  {
    _id: undefined,
    sku: "SPRKD",
    manufacturer: "NGK",
    name: "Spark Plugs (Set of 4)",
    description: "Premium spark plugs for reliable ignition",
    longDescription:
      "Premium spark plugs designed for optimal combustion and engine performance. These plugs feature a durable ceramic insulator and superior spark gap consistency, ensuring reliable ignition across all RPM ranges.",
    price: 599,
    originalPrice: 799,
    category: "Engine Parts",
    images: [
      "https://images.unsplash.com/photo-1494537285001-ee57a67af1f1?w=500&h=500&fit=crop",
      "https://images.unsplash.com/photo-1494537285001-ee57a67af1f1?w=500&h=500&fit=crop&q=80",
    ],
    specifications: [
      { key: "Type", value: "Copper Core" },
      { key: "Gap Size", value: "1.1mm" },
      { key: "Heat Range", value: "7" },
      { key: "Quantity", value: "4 Pieces" },
    ],
    inventory: 200,
    rating: 4.5,
    reviewCount: 134,
    isFeatured: true,
    createdAt: new Date("2024-01-30"),
    updatedAt: new Date("2024-02-04"),
  },
  {
    _id: undefined,
    sku: "BATE",
    manufacturer: "Exide",
    name: "Car Battery 60Ah",
    description: "High-capacity battery with superior cranking power",
    longDescription:
      "Heavy-duty car battery with exceptional starting power and reliability. Features advanced plate design for increased power output and longer service life. Ideal for modern vehicles with multiple electrical demands.",
    price: 3999,
    originalPrice: 4999,
    category: "Electrical",
    images: [
      "https://images.unsplash.com/photo-1533994242443-8f0cb6f35b4f?w=500&h=500&fit=crop",
      "https://images.unsplash.com/photo-1533994242443-8f0cb6f35b4f?w=500&h=500&fit=crop&q=80",
    ],
    specifications: [
      { key: "Capacity", value: "60 Ah" },
      { key: "Voltage", value: "12V" },
      { key: "Cranking Power", value: "600 CCA" },
      { key: "Warranty", value: "36 Months" },
    ],
    inventory: 45,
    rating: 4.7,
    reviewCount: 267,
    isFeatured: true,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-05"),
  },
  {
    _id: undefined,
    sku: "SUSPF",
    manufacturer: "KYB",
    name: "Suspension Coil Spring",
    description: "OEM-quality suspension springs for smooth ride",
    longDescription:
      "Premium suspension coil springs manufactured to OEM specifications. Provides consistent ride comfort and excellent load-bearing capacity. Designed to minimize vibration and ensure stability on all road conditions.",
    price: 2499,
    originalPrice: 3299,
    category: "Suspension",
    images: [
      "https://images.unsplash.com/photo-1586139207252-7e90a8a08bdc?w=500&h=500&fit=crop",
      "https://images.unsplash.com/photo-1586139207252-7e90a8a08bdc?w=500&h=500&fit=crop&q=80",
    ],
    specifications: [
      { key: "Type", value: "Helical Spring" },
      { key: "Position", value: "Front/Rear" },
      { key: "Load Capacity", value: "500kg" },
      { key: "Material", value: "Alloy Steel" },
    ],
    inventory: 60,
    rating: 4.6,
    reviewCount: 89,
    isFeatured: false,
    createdAt: new Date("2024-02-02"),
    updatedAt: new Date("2024-02-06"),
  },
  {
    _id: undefined,
    sku: "WIPEG",
    manufacturer: "RainX",
    name: "Windshield Wiper Blades",
    description: "All-weather wiper blades for clear visibility",
    longDescription:
      "Advanced wiper blades with all-weather performance. Featuring aerodynamic design and natural rubber squeegee, these blades provide streak-free wiping in rain, snow, and dry conditions.",
    price: 449,
    originalPrice: 599,
    category: "Exterior",
    images: [
      "https://images.unsplash.com/photo-1550355291-bbee04a92027?w=500&h=500&fit=crop",
      "https://images.unsplash.com/photo-1550355291-bbee04a92027?w=500&h=500&fit=crop&q=80",
    ],
    specifications: [
      { key: "Length", value: '24" & 18"' },
      { key: "Type", value: "All-Weather" },
      { key: "Material", value: "Natural Rubber" },
      { key: "Durability", value: "1 Year" },
    ],
    inventory: 180,
    rating: 4.4,
    reviewCount: 203,
    isFeatured: true,
    createdAt: new Date("2024-02-03"),
    updatedAt: new Date("2024-02-07"),
  },
  {
    _id: undefined,
    sku: "MATH",
    manufacturer: "WeatherTech",
    name: "Car Floor Mats Set",
    description: "Premium rubber mats with anti-slip backing",
    longDescription:
      "Premium quality floor mats crafted from durable rubber with anti-slip backing. Protects your car interior from dirt, water, and wear. Easy to clean and maintain, these mats fit most vehicle models.",
    price: 1899,
    originalPrice: 2499,
    category: "Interior",
    images: [
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=500&fit=crop",
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=500&fit=crop&q=80",
    ],
    specifications: [
      { key: "Material", value: "Rubber with EVA" },
      { key: "Pieces", value: "4 Mats" },
      { key: "Anti-Slip Backing", value: "Yes" },
      { key: "Easy Clean", value: "Yes" },
    ],
    inventory: 95,
    rating: 4.5,
    reviewCount: 142,
    isFeatured: true,
    createdAt: new Date("2024-02-04"),
    updatedAt: new Date("2024-02-08"),
  },
  {
    _id: undefined,
    sku: "FLUIDI",
    manufacturer: "Castrol",
    name: "Transmission Fluid",
    description: "Synthetic transmission fluid for smooth shifting",
    longDescription:
      "High-quality synthetic transmission fluid engineered for optimal gear protection and smooth shifting. Provides excellent thermal stability and extends transmission life. Suitable for both automatic and manual transmissions.",
    price: 649,
    originalPrice: 849,
    category: "Transmission",
    images: [
      "https://images.unsplash.com/photo-1584345604966-84b12b846c97?w=500&h=500&fit=crop",
      "https://images.unsplash.com/photo-1584345604966-84b12b846c97?w=500&h=500&fit=crop&q=80",
    ],
    specifications: [
      { key: "Type", value: "Synthetic" },
      { key: "Volume", value: "1 Liter" },
      { key: "Viscosity", value: "ATF" },
      { key: "Compatibility", value: "Universal" },
    ],
    inventory: 140,
    rating: 4.6,
    reviewCount: 95,
    isFeatured: false,
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-09"),
  },
];

export const DUMMY_REVIEWS: Review[] = [
  {
    _id: undefined,
    productId: undefined!,
    userId: undefined!,
    userName: "Rajesh Kumar",
    rating: 5,
    title: "Excellent product quality",
    comment:
      "Very satisfied with the product. It works perfectly and the delivery was fast. Highly recommended!",
    verified: true,
    helpful: 45,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    _id: undefined,
    productId: undefined!,
    userId: undefined!,
    userName: "Priya Sharma",
    rating: 4,
    title: "Good value for money",
    comment:
      "Good product quality at a reasonable price. Delivery could have been faster but overall satisfied.",
    verified: true,
    helpful: 32,
    createdAt: new Date("2024-01-28"),
    updatedAt: new Date("2024-01-28"),
  },
];
